### ISSUE TITLE
Science from nothing

### ISSUE THREAD

**Issue by boomshroom** [refulgence/simultaneous-research#2]
Under rare circumstances, research progress can be made for technologies that you lack the science pack for. I observed this when a technology requiring promethium science finished researching despite it not being automated nor did I have enough stockpiled to research it. I was in parallel research mode at the time.

Looking at the code, it seems as though if a lab was assigned a technology, but lacks the required science packs, it will fail to remove enough from its inventory, but will still decrement the full amount, leading to a small amount of borrowed research being done. It seems like this should get caught on future iterations, but it's possible that it's not actually and is instead accumulating large amounts of science pack debt.

**Comment by refulgence** [comment]
I don't really understand how this could happen. Lab inventories can go negative, and science pack debts would need to get paid before the lab gets to research a tech requiring these science packs.

Certain inaccuracies are present, but they should theoretically average out over the course of the game so I didn't saw a point in complicating calculations too much.

Can you check if any of your labs have massively negative amounts of any stored science packs? You can use /sr_list_labs command, it should work fine if you have ~30 labs or less. Or upload your save somewhere and I'll check it.

It could also be a bug with progress calculation, I guess, but it looks like it's working fine on my end.

Gotta need more information here. Can you reproduce it?

**Comment by boomshroom** [comment]
I have more than 30 labs (101), so the debug print can't show all of them, but I think it was enough to show what was actually going on. I think the promethium science was buffered by the mod, so it looked like I didn't have any in the labs, but the debug command showed that despite that, there were some labs with a positive amount of promethium science (and science from the Tenebris modded planet, which I don't have automated either) buffered. It could be that I wasn't able to research the techs normally because the packs were already buffered during prior experiments with the mod.

I still didn't think the amount I had buffered should've been enough to complete any technologies, so there's still a chance that there could be an inaccuracy, though once the buffer was completely drained, all research with those science packs stopped.

**Comment by boomshroom** [comment]
Ironically, the production graph behavior that I was complaining about is what confirmed this, since the consumption of promethium science now matches the produced science closely enough for me to attribute the difference to those prior experiments, and the number of consumed packs matches with the number of units researched for the techs I was testing with.
